formatting change.
jasjs1/ProPass pull request #10
Opened 2023-02-05 21:27 UTC by 1jaycesagvold1

I fixed a a few incorrect capitolizations, and weak from a line.

2023-02-05 21:28 UTC, jSagvold28 requested changes
It would be cool if there was animojis

2023-02-05 21:28 UTC, 1jaycesagvold1 commented
Yeah that would be cool! Working on that now!

2023-02-09 01:30 UTC, jSagvold28 approved these changes

2023-02-15 00:30 UTC, jSagvold28 approved these changes

2023-02-15 00:30 UTC, closed without merging